// <auto-generated />
namespace Mabe3aty.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class productModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202110301943079_productModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
